language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

notifications:
  email: false

before_install:
  - ./gradlew -v

script:
  - ./gradlew clean assembleDebug

sudo: false
